version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: sistema-gtr-mecanica
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?err}
      POSTGRES_USER: ${POSTGRES_USER:?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
